### ISSUE TITLE
[Feature] Add a right-click option to the worskpace status bar item with a context menu that allows a "quick save"

### ISSUE THREAD

**Issue by GitMurf** [nothingislost/obsidian-workspace-picker#14]
Basically there are many times I want to "save" my workspace as I go to save current state and continue working. It is a bit of "work" to open up the workspace modal and then do shift + Enter on your current workspace item. It would be great, and feels natural, to have the ability to right-click the workspace status bar element and a context menu pop up appear that says something like "Save current workspace". Then can much more quickly, without much friction / distraction, save my workspace without needing the modal to pop up and use shift + Enter.

**Comment by nothingislost** [comment]
What about just auto saving when shift-clicking the status bar icon? It'll be easier for now until we get more actions to justify a full context menu.

**Comment by GitMurf** [comment]
Yeah that works for me!

**Comment by nothingislost** [comment]
Shift click on the status bar icon was delivered in the latest version
