### ISSUE TITLE
[Feature] Instead of doing shift + delete to delete an item, add a delete icon

### ISSUE THREAD

**Issue by GitMurf** [nothingislost/obsidian-workspace-picker#16]
It would be nice to instead of having the shift + delete shortcut, to have a delete icon. In my scsreenshot I drew an "x" but in a perfect world would be like a trash can icon or a more classic delete icon.

![image](https://user-images.githubusercontent.com/64155612/132891210-2d0dab8d-4abb-4a80-91cd-775febc91806.png)

**Comment by nothingislost** [comment]
Addressed in the next release 
![image](https://user-images.githubusercontent.com/89109712/132902211-74019eee-f810-4391-963f-7f436c141e58.png)

**Comment by nothingislost** [comment]
Or this? I'm open to icons. I've been picking from https://remixicon.com/
![image](https://user-images.githubusercontent.com/89109712/132902537-60a4e02d-2b20-4e45-af3c-4a469952416d.png)

**Comment by jsmorabito** [comment]
implemented in 0.0.8

**Comment by GitMurf** [comment]
I like the trash can icon best :)

btw you know obsidian gives access to a bunch of icons out of the box right? You can use the icon swapper plugin to see a list of all of them and their names you reference with set-icon from obsidian api.

**Comment by GitMurf** [comment]
![725C2B24-369F-40B4-BDAE-C1F85D9EF371](https://user-images.githubusercontent.com/64155612/132912756-658a4576-d1db-460c-ab2f-a738ce292afb.png)

**Comment by GitMurf** [comment]
Here it is in the api: https://github.com/obsidianmd/obsidian-api/blob/bde556afa033e909ebfb9fcee8f5ef288276f78f/obsidian.d.ts#L2476
