### ISSUE TITLE
Reduce padding for even spacing on the status bar with other items

### ISSUE THREAD

**Issue by jsmorabito** [nothingislost/obsidian-workspace-picker#4]
<img width="521" alt="image" src="https://user-images.githubusercontent.com/46250921/132568554-53827099-00b2-4899-891e-f8a596dbbd6b.png">

I think this is the element that needs the padding removed:
<img width="795" alt="image" src="https://user-images.githubusercontent.com/46250921/132569067-87d15824-23a9-4f97-99c9-f5dbf8983aa0.png">

**Comment by nothingislost** [comment]
That's the standard padding for any item in the status bar. I'll leave it up to themes to change that.

I am changing the way that is displayed in the status bar though. It looks like this now:

![image](https://user-images.githubusercontent.com/89109712/132576905-5733c236-6ee9-437c-9321-df17f5c86abf.png)

**Comment by jsmorabito** [comment]
> That's the standard padding for any item in the status bar. I'll leave it up to themes to change that.
> 
> I am changing the way that is displayed in the status bar though. It looks like this now:
> 
> ![image](https://user-images.githubusercontent.com/89109712/132576905-5733c236-6ee9-437c-9321-df17f5c86abf.png)

awesome looks good!
