### ISSUE TITLE
[bug] multiple focus states in edit mode

### ISSUE THREAD

**Issue by jsmorabito** [nothingislost/obsidian-workspace-picker#8]
<img width="253" alt="image" src="https://user-images.githubusercontent.com/46250921/132873707-ba45b877-d3f1-42f0-8b05-8720b9df8877.png">

**Comment by nothingislost** [comment]
I imagine you clicked on rename for all of the workspaces there? Would would you expect the behavior to be when doing that?

**Comment by jsmorabito** [comment]
> I imagine you clicked on rename for all of the workspaces there? What would you expect the behavior to be when doing that?

Yes, my expected behavior is that there will only be one edit focus state active at a time. And actually that is true, but the focus border is left on with the workspaces who's edit buttons were previously clicked. I should only see the "currently being edited" workspace having the focus border

**Comment by nothingislost** [comment]
Gotcha. Fix incoming in next release.

**Comment by nothingislost** [comment]
Try out https://github.com/nothingislost/obsidian-workspace-picker/releases/tag/0.0.7
